export const REQUEST_RECORDING_PLAYLIST = 'REQUEST_RECORDING_PLAYLIST'
export const RECEIVE_RECORDING_PLAYLIST = 'RECEIVE_RECORDING_PLAYLIST'
export const RECEIVE_RECORDING_PLAYLIST_FAILURE = 'RECEIVE_RECORDING_PLAYLIST_FAILURE'

export const SET_CURRENT_FRAME = 'SET_CURRENT_FRAME'
